# SPDX-License-Identifier: MIT
# ALSA output of wallpanel-airplay: 44.1 kHz (shairport-sync without FFmpeg only outputs 44100/S16/2)
# into the shared 48 kHz dmix of /etc/asound.conf, so Chromium keeps playing alongside.
# An explicit rate plugin instead of "default": shairport-sync probes with resampling disabled
# (snd_pcm_hw_params_set_rate_resample 0), which makes the plug in "default" refuse 44100.
pcm.wallpanel_airplay {
	type rate
	slave {
		pcm "wallpanel_dmix"
		rate 48000
	}
	hint { show on description "Wallpanel speaker for AirPlay (44.1 kHz -> dmix 48 kHz)" }
}
