# Shared helpers for install.sh / sync-apps.sh / build-*.sh (sourced; expects $P = repo root).

# ssh_pubkeys: print the maintenance public keys (tools/ssh/*.pub, gitignored).
# Creates the project key on first use, so every checkout authorizes only its own key.
ssh_pubkeys() {
	[ -f "$P/tools/ssh/id_ed25519" ] ||
		ssh-keygen -q -t ed25519 -N '' -C wallpanel-maintenance -f "$P/tools/ssh/id_ed25519" >&2
	cat "$P"/tools/ssh/*.pub
}

# push_rootfs SSH ROOT: copy system/rootfs/overlay, apps/*/rootfs, wallpanel-rebootmode and the
# maintenance keys into ROOT on the device.
push_rootfs() {
	local ssh=$1 r=$2 a
	[ -x "$P/build/out/rebootmode" ] || { echo "error: run ./build.sh helpers first" >&2; return 1; }
	tar --owner=0 --group=0 -cf - -C "$P/system/rootfs/overlay" . | $ssh "tar -xf - -C $r"
	for a in "$P"/apps/*/rootfs; do
		tar --owner=0 --group=0 --exclude=__pycache__ -cf - -C "$a" . | $ssh "tar -xf - -C $r"
	done
	$ssh "cat > $r/usr/sbin/wallpanel-rebootmode" < "$P/build/out/rebootmode"
	ssh_pubkeys | $ssh "mkdir -p $r/root/.ssh; cat > $r/root/.ssh/authorized_keys"
	$ssh "cd $r && chmod 755 etc/init.d/wallpanel-* usr/lib/wallpanel/wallpanel-kiosk.sh usr/sbin/wallpanel-update usr/sbin/wallpanel-rebootmode
		chmod 700 root/.ssh; chmod 600 root/.ssh/authorized_keys"
}

# write_conf SSH ROOT: ROOT/etc/wallpanel/wallpanel.conf and trusted certificates (tools/trust/*.crt)
# from tools/local.env. Values are single-quoted: the kiosk sources the file as shell, passwords
# may contain shell characters (a single quote itself is not supported).
write_conf() {
	local ssh=$1 r=$2 k v
	{
		echo "# generated by tools/install.sh / tools/sync-apps.sh from tools/local.env"
		for k in URL ROTATION OUTPUT DEVICE_NAME MQTT_HOST MQTT_PORT MQTT_USER MQTT_PASSWORD KIOSK_USER KIOSK_PASSWORD; do
			case $k in
			URL) v=${KIOSK_URL:-${HA_URL:-}} ;;
			ROTATION) v=${ROTATION:-180} ;;
			OUTPUT) v=${OUTPUT:-DSI-1} ;;
			DEVICE_NAME) v=${DEVICE_NAME:-Wallpanel} ;;
			MQTT_PORT) v=${MQTT_PORT:-1883} ;;
			*) eval "v=\${$k:-}" ;;
			esac
			case $v in *\'*) echo "error: $k must not contain a single quote" >&2; return 1 ;; esac
			printf "%s='%s'\n" "$k" "$v"
		done
	} | $ssh "umask 027; mkdir -p $r/etc/wallpanel/trust; chmod 755 $r/etc/wallpanel/trust; cat > $r/etc/wallpanel/wallpanel.conf.new &&
		chown root:\$(sed -n 's/^wallpanel:[^:]*:\([0-9]*\):.*/\1/p' $r/etc/group) $r/etc/wallpanel/wallpanel.conf.new &&
		mv $r/etc/wallpanel/wallpanel.conf.new $r/etc/wallpanel/wallpanel.conf"
	# time zone (tools/local.env TIMEZONE, e.g. Europe/Berlin): the reboot/update time is local time
	[ -n "${TIMEZONE:-}" ] && $ssh "[ -f $r/usr/share/zoneinfo/$TIMEZONE ] && ln -sf /usr/share/zoneinfo/$TIMEZONE $r/etc/localtime && echo $TIMEZONE > $r/etc/timezone"
	for c in "$P"/tools/trust/*.crt; do
		[ -f "$c" ] && $ssh "cat > $r/etc/wallpanel/trust/$(basename "$c"); chmod 644 $r/etc/wallpanel/trust/$(basename "$c")" < "$c"
	done
	return 0
}

# set_root_password SSH ROOT: store the SHA-512 hash of ROOT_PASSWORD (tools/local.env) in ROOT/etc/shadow.
# Without ROOT_PASSWORD the root password is locked (key login only).
set_root_password() {
	local h='!'
	[ -n "${ROOT_PASSWORD:-}" ] && h=$(openssl passwd -6 -stdin <<<"$ROOT_PASSWORD")
	printf '%s\n' "$h" | $1 "read -r h; sed -i \"s|^root:[^:]*:|root:\$h:|\" $2/etc/shadow; grep -c '^root:\\\$6\\\$' $2/etc/shadow >/dev/null && echo 'root password set' || echo 'root password locked'"
}

# apk_key: path of the local apk signing key (tools/apk-key/*.rsa, gitignored), created on first use.
# Its public half (*.rsa.pub) goes to /etc/apk/keys on the device, so our own packages (./build.sh cage)
# install without --allow-untrusted. Every checkout signs with its own key.
apk_key() {
	local k
	k=$(ls "$P"/tools/apk-key/*.rsa 2>/dev/null | head -1)
	if [ -z "$k" ]; then
		mkdir -p "$P/tools/apk-key" && chmod 700 "$P/tools/apk-key"
		k=$P/tools/apk-key/wallpanel-$(openssl rand -hex 4).rsa
		(umask 077 && openssl genrsa -out "$k" 4096 2> /dev/null)
		openssl rsa -in "$k" -pubout -out "$k.pub" 2> /dev/null
	fi
	echo "$k"
}

# cage_version: <pkgver>-r<pkgrel> of our cage package (system/cage/APKBUILD)
cage_version() {
	echo "$(sed -n 's/^pkgver=//p' "$P/system/cage/APKBUILD")-r$(sed -n 's/^pkgrel=//p' "$P/system/cage/APKBUILD")"
}

# install_apk SSH ROOT NAME VERSION: install our own build/out/NAME-VERSION.apk into ROOT on the device,
# with our public key in ROOT/etc/apk/keys, and pin the exact version in ROOT/etc/apk/world
# ("NAME=VERSION"): the package is in no repository, the pin also keeps apk upgrade from replacing it.
install_apk() {
	local ssh=$1 r=$2 n=$3 v=$4 k a
	k=$(apk_key) a=$P/build/out/$n-$v.apk
	[ -f "$a" ] || { echo "error: $a missing - run ./build.sh $n first" >&2; return 1; }
	$ssh "mkdir -p $r/etc/apk/keys && cat > $r/etc/apk/keys/$(basename "$k").pub" < "$k.pub"
	$ssh "cat > $r/tmp/$n-$v.apk" < "$a"
	$ssh "apk --root $r add --wait 300 -q $r/tmp/$n-$v.apk && apk --root $r add --wait 300 -q '$n=$v'; rc=\$?; rm -f $r/tmp/$n-$v.apk
		[ \$rc = 0 ] && grep -qx '$n=$v' $r/etc/apk/world && apk --root $r info -e -v $n | grep -qx '$n-$v'" ||
		{ echo "error: installing $n $v failed" >&2; return 1; }
	echo "$n $v installed, pinned in /etc/apk/world"
}

# install_cage SSH ROOT: our cage (./build.sh cage); the world pin keeps apk upgrade from switching to
# Alpine's cage (no gamma control).
install_cage() { install_apk "$1" "$2" cage "$(cage_version)"; }

# gamma_version: <pkgver>-r<pkgrel> of wallpanel-gamma (system/wallpanel-gamma/APKBUILD)
gamma_version() {
	echo "$(sed -n 's/^pkgver=//p' "$P/system/wallpanel-gamma/APKBUILD")-r$(sed -n 's/^pkgrel=//p' "$P/system/wallpanel-gamma/APKBUILD")"
}

# install_gamma SSH ROOT: our wallpanel-gamma (./build.sh wallpanel-gamma)
install_gamma() { install_apk "$1" "$2" wallpanel-gamma "$(gamma_version)"; }
